//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElasticSearch {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElasticSearch.CodeResource", typeof(CodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ## Ignore Visual Studio temporary files, build results, and
        ///## files generated by popular Visual Studio add-ons.
        ///
        ///# User-specific files
        ///*.suo
        ///*.user
        ///*.userosscache
        ///*.sln.docstates
        ///
        ///# User-specific files (MonoDevelop/Xamarin Studio)
        ///*.userprefs
        ///
        ///# Build results
        ///[Dd]ebug/
        ///[Dd]ebugPublic/
        ///[Rr]elease/
        ///[Rr]eleases/
        ///x64/
        ///x86/
        ///bld/
        ///[Bb]in/
        ///[Oo]bj/
        ///[Ll]og/
        ///
        ///# Visual Studio 2015 cache/options directory
        ///.vs/
        ///# Uncomment if you have tasks that create the project&apos;s static files in wwwroot
        ///#ww [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CSharpGitIgnore {
            get {
                return ResourceManager.GetString("CSharpGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Infrastructure_dll {
            get {
                object obj = ResourceManager.GetObject("Infrastructure_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Infrastructure&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Infrastructure.BuiltInAnalyzer&quot;&gt;
        ///            &lt;summary&gt;
        ///            内置分词器
        ///            https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-analyzers.html
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;F:Infrastructure.BuiltInAnalyzer.NONE&quot;&gt;
        ///            &lt;summary&gt;
        ///            未设置
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;me [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Infrastructure_xml {
            get {
                return ResourceManager.GetString("Infrastructure_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 target/
        ///.idea/
        ///.project
        ///*.iml
        /// 的本地化字符串。
        /// </summary>
        internal static string JavaGitIgnore {
            get {
                return ResourceManager.GetString("JavaGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pushd CodeFirst
        ///dotnet restore
        ///dotnet build
        ///popd
        ///
        ///rmdir /S /Q Java
        ///rmdir /S /Q Mappings
        ///
        ///elasticsearch update
        ///
        ///pause
        /// 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
